---
title: "CodeBook"
author: "Qureish Lalani"
date: "05/10/2016"
output: html_document
---

#Raw Data


The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

| tBodyAcc-XYZ
| tGravityAcc-XYZ
| tBodyAccJerk-XYZ
| tBodyGyro-XYZ
| tBodyGyroJerk-XYZ
| tBodyAccMag
| tGravityAccMag
| tBodyAccJerkMag
| tBodyGyroMag
| tBodyGyroJerkMag
| fBodyAcc-XYZ
| fBodyAccJerk-XYZ
| fBodyGyro-XYZ
| fBodyAccMag
| fBodyAccJerkMag
| fBodyGyroMag
| fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

| mean(): Mean value
| std(): Standard deviation
| mad(): Median absolute deviation 
| max(): Largest value in array
| min(): Smallest value in array
| sma(): Signal magnitude area
| energy(): Energy measure. Sum of the squares divided by the number of values. 
| iqr(): Interquartile range 
| entropy(): Signal entropy
| arCoeff(): Autorregresion coefficients with Burg order equal to 4
| correlation(): correlation coefficient between two signals
| maxInds(): index of the frequency component with largest magnitude
| meanFreq(): Weighted average of the frequency components to obtain a mean frequency
| skewness(): skewness of the frequency domain signal 
| kurtosis(): kurtosis of the frequency domain signal 
| bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
| angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

| gravityMean
| tBodyAccMean
| tBodyAccJerkMean
| tBodyGyroMean
| tBodyGyroJerkMean

## The variables have no measure unit since they are normalized.

### Merge the training and the test sets to create one data set.

| The feature vectors are split in "X_train.txt" and "X_test.txt", I loaded them into `xTrain` and `xTest` then merged them into the matrix `X` using `bind_rows`. 
| The same is for the activity labels "Y_train.txt" and "Y_test.txt" and subject labels "subject_train.txt" and "subject_test.txt"

### Extract only the measurements on the mean and standard deviation for each measurement

| The file "features.txt" contains the variable names for each feature in X.
| I loaded the file in the variable `feat`
| Using `filter` and `grepl` I extracted only the variables for mean and standard deviation from the matrix X.

### Use descriptive activity names to name the activities in the data set

| The file "activity_labels.txt" contains the labels for the activities so I assigned them to the vector of activities:
         `Y$V1<-activities[Y$V1,2]`
         
### Appropriately labels the data set with descriptive variable names.  

| The variable names for `X` are in `feat`.

### Create a second, independent tidy data set with the average of each variable

| I binded the `activity` and `subject` vector along with the measurements matrix and transformed the result into a `tbl_df`.
| Using pipelines `%>%` I grouped the table by `activity` and `subject` and sumarized the mean for each measurement.
| The resulting data table is stored in `tidyData.txt`
